<center><h1> Numpy Assignemnt </h1></center>

### Write the Code in empty cells to produce it's exact below output

## Import Numpy

In [1]:
import numpy as np

## Creating 3 Arrays (1-D, 2-D, 3-D)

In [3]:
one_d_arr=np.array([1,5,7,4])
one_d_arr

array([1, 5, 7, 4])

In [5]:
two_d_arr=np.array([[1,2,5],
                    [4,6,9]])
two_d_arr

array([[1, 2, 5],
       [4, 6, 9]])

In [6]:
three_d_arr=np.array([[[1,3,5],
                       [4,9,10],
                       [5,3,2]],
                      [[4,6,10],
                       [5,9,8],
                       [10,3,4]]])
three_d_arr

array([[[ 1,  3,  5],
        [ 4,  9, 10],
        [ 5,  3,  2]],

       [[ 4,  6, 10],
        [ 5,  9,  8],
        [10,  3,  4]]])

## Use attributes of Numpy (ndim, shape, size, dtype, itemsize) for all above 3 arrays

In [ ]:
one_d_arr.ndim
one_d_arr.shape
one_d_arr.size
type(one_d_arr)
one_d_arr.itemsize

4

In [22]:
two_d_arr.ndim
two_d_arr.shape
two_d_arr.size
type(two_d_arr)
two_d_arr.itemsize

4

In [28]:
three_d_arr.ndim
three_d_arr.shape
three_d_arr.size
three_d_arr.itemsize
type(three_d_arr)

numpy.ndarray

## Create Range Arrays

In [116]:
# This matrix (5x5) will have elements within the range of 0-99 with step size of 4


In [50]:
matrix_1=np.arange(0,100,4).reshape(5,5)
matrix_1

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

## Creating a Random array within range of 0-50

In [120]:
# This Matrix (4x6) will have random integers within range 0-50


In [62]:
matrix_2= np.random.randint(0,51,size=(4,6))
matrix_2

array([[28, 16, 33,  3, 34, 33],
       [45, 38, 10,  6,  5, 43],
       [49, 28, 38, 50, 43, 42],
       [14,  1, 36, 28, 17, 38]])

## Creating a Random array within range of 0.0 and 1.0 (Float)

In [122]:
# This 2x3 Matrix will have the float range from 0.0 to 1.0


In [77]:
matrix_3=np.random.rand(2,3)
matrix_3

array([[0.599285  , 0.78111533, 0.36944896],
       [0.89159734, 0.28539161, 0.62793388]])

In [78]:
type(matrix_3[0][0])

numpy.float64

## Array Indexing

In [88]:
# Create the follwing array
matrix_4=np.random.randint(0,51,size=(4,6))
matrix_4

array([[49, 33, 40, 28,  8, 29],
       [42, 16, 45, 25, 46,  2],
       [34, 30, 33,  7, 24, 45],
       [20,  6,  6, 42,  1, 24]])

In [89]:
## Return Unique Elements in the array
unique_elements=np.unique(matrix_4)
unique_elements

array([ 1,  2,  6,  7,  8, 16, 20, 24, 25, 28, 29, 30, 33, 34, 40, 42, 45,
       46, 49])

In [90]:
# Return the First Row (Indexing starts with 0)
matrix_4[0]

array([49, 33, 40, 28,  8, 29])

In [96]:
# Return 3rd Row 3rd Element (Indexing starts with 0)
matrix_4[2][2]

33

In [97]:
# Returns 1st Row 4th Element (Indexing starts with 0)
matrix_4[0][3]

28

In [ ]:
# Create the follwoing array
arr_1=np.array([[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],

                [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]]])
arr_1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [101]:
# Return 1st array
arr_1[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
# Returns 1st array 2nd row 3rd element
arr_1[0,1,2]

5

## Array Slicing

<h4> <b> Slicing 1-Dimensional Arrays </b> </h4>

In [125]:
# Create the 1-Dimensional array 
one_D=np.array([1,5,7,4])
one_D

array([1, 5, 7, 4])

In [126]:
# Produce the follwing Result
one_D[2:5]

array([7, 4])

<h4> <b> Slicing 2-Dimensional Arrays </b> </h4>

In [128]:
# Create the 2-Dimensional array 
two_D=np.array([[15, 42, 41, 38, 49,  3],
                [13,  8, 25, 25, 48,  5],
                [34, 22, 12, 37, 26, 48],
                [31, 30, 46, 40,  5, 40]])
two_D

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [136]:
# Produce the follwoing result
two_D[0:4,1:3]

array([[42, 41],
       [ 8, 25],
       [22, 12],
       [30, 46]])

In [138]:
# Produce the follwoing result
two_D[0:3,0:3]

array([[15, 42, 41],
       [13,  8, 25],
       [34, 22, 12]])

In [140]:
# Produce the following result
two_D[1:3,3:5]

array([[25, 48],
       [37, 26]])

## Assigning Values to Arrays (Broadcasting)

<h4> <b> 1-Dimensional Arrays Broadcasting </b> </h4>

In [143]:
# Create 1-D Array
one_d=np.array([1,5,7,4])
one_d

array([1, 5, 7, 4])

In [144]:
# Change Index 3 value to 99
one_d[3]=99
one_d

array([ 1,  5,  7, 99])

In [146]:
# Change the Index vales by slicing
one_d[1:5]=888
one_d

array([  1, 888, 888, 888])

<h4> <b> 2-Dimensional Arrays Broadcasting </b> </h4>

In [157]:
# Create the 2-D Array
two_d=np.array([[1, 2, 5],
                [4, 6, 9]])
two_d

array([[1, 2, 5],
       [4, 6, 9]])

In [158]:
# Change 1st row 2nd value 2 to 100
two_d[0,1]=100
two_d

array([[  1, 100,   5],
       [  4,   6,   9]])

In [160]:
# Change values by slicing the matrix and produce the follwoing results
two_d[0,1:3]=777
two_d

array([[  1, 777, 777],
       [  4,   6,   9]])

## Numpy Operations

<h4> <b> Arithmetic Operations </b> </h4>

In [162]:
# Create the follwoing array
new_arr=np.array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])
new_arr

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [165]:
# Add +10 to each element
add_arr=new_arr+10
add_arr

array([[25, 52, 51, 48, 59, 13],
       [23, 18, 35, 35, 58, 15],
       [44, 32, 22, 47, 36, 58],
       [41, 40, 56, 50, 15, 50]])

In [168]:
# Subtract -10 from each element
sub_arr=new_arr-10
sub_arr

array([[ 5, 32, 31, 28, 39, -7],
       [ 3, -2, 15, 15, 38, -5],
       [24, 12,  2, 27, 16, 38],
       [21, 20, 36, 30, -5, 30]])

In [169]:
# Multiplying each element with 9
multiply_arr=new_arr*9
multiply_arr

array([[135, 378, 369, 342, 441,  27],
       [117,  72, 225, 225, 432,  45],
       [306, 198, 108, 333, 234, 432],
       [279, 270, 414, 360,  45, 360]])

In [170]:
# Dividing each element with 2
divide_arr=new_arr/2
divide_arr

array([[ 7.5, 21. , 20.5, 19. , 24.5,  1.5],
       [ 6.5,  4. , 12.5, 12.5, 24. ,  2.5],
       [17. , 11. ,  6. , 18.5, 13. , 24. ],
       [15.5, 15. , 23. , 20. ,  2.5, 20. ]])

<h4> <b> Statistical Operations </b> </h4>

In [172]:
# Creating a New Array
new_array=np.array([[ 2,  3,  4],
       [ 4,  3, 17],
       [89, 33, 12]])
new_array

array([[ 2,  3,  4],
       [ 4,  3, 17],
       [89, 33, 12]])

In [194]:
# Sum Operations
# Produce total sum, row wise sum (first elements), columns wise sum

col_sum=np.sum(new_array,axis=0)
col_sum

row_sum=np.sum(new_array,axis=1)
row_sum

total_sum=np.sum(new_array)
total_sum

result=(total_sum,col_sum,row_sum)
print(result)


(167, array([95, 39, 33]), array([  9,  24, 134]))


In [209]:
# Calculate Mean, Meadian, Square root, minimum, maximum values of new_arr
arr_mean=np.mean(new_array)
arr_mean

arr_median=np.median(new_array)
arr_median

arr_sqrt=np.sqrt(new_array)
arr_sqrt

arr_min=np.min(new_array)
arr_min

arr_max=np.max(new_array)
arr_max

result=(arr_mean,arr_median,arr_sqrt,arr_min,arr_max)
print(result)

(18.555555555555557, 4.0, array([[1.41421356, 1.73205081, 2.        ],
       [2.        , 1.73205081, 4.12310563],
       [9.43398113, 5.74456265, 3.46410162]]), 2, 89)
